version: '3.4'

services:
  urlshortener.api:
    image: ${DOCKER_REGISTRY-}urlshortenerapi
    build:
      context: .
      dockerfile: UrlShortener.API/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserverdb
    ports:
      - "1450:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Reli!@#456
  redis:
    image: redis
    container_name: myredis
    ports:
      - "6380:6379"
